# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76fb0e07a7a0a79e347ecacf791617178688eeacda15b63f09091e9de5d6c49ecaebb46a5bd8eab0e4f9c7fadb439a0a7aba39c96c7c32f32aace4ec64eb4173

test:
  secret_key_base: 463612537e193f2b34ad69183482e48d090673de197fef1ee549d58f3071ec792b1a9e14690f140c1f4e1c520a9c625403aef9b8c180dcab8f0363a1dba5aa4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
